// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABWMEjWFXSLc-7V28-VM27sW-DuWAzF8k',
    appId: '1:877415687199:ios:9c603bc25b483cdef3a12a',
    messagingSenderId: '877415687199',
    projectId: 'smart-assistive-navigation',
    storageBucket: 'smart-assistive-navigation.firebasestorage.app',
    iosBundleId: 'com.example.blindAssistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQlFmWGuHXovmFFlLusm8ompYk_82uCYU',
    appId: '1:877415687199:web:78b3051432356a70f3a12a',
    messagingSenderId: '877415687199',
    projectId: 'smart-assistive-navigation',
    authDomain: 'smart-assistive-navigation.firebaseapp.com',
    storageBucket: 'smart-assistive-navigation.firebasestorage.app',
    measurementId: 'G-18GY85K93F',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQlFmWGuHXovmFFlLusm8ompYk_82uCYU',
    appId: '1:877415687199:web:78b3051432356a70f3a12a',
    messagingSenderId: '877415687199',
    projectId: 'smart-assistive-navigation',
    authDomain: 'smart-assistive-navigation.firebaseapp.com',
    storageBucket: 'smart-assistive-navigation.firebasestorage.app',
    measurementId: 'G-18GY85K93F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF7Fm7IcFN4QOEIryidC0Tm78Pq48BB8o',
    appId: '1:877415687199:android:a2a1f9dd8f07ab80f3a12a',
    messagingSenderId: '877415687199',
    projectId: 'smart-assistive-navigation',
    storageBucket: 'smart-assistive-navigation.firebasestorage.app',
  );

}